# @file: config/content/posts.example.yaml
# @description: Пример конфигурации постов Neurohod (для редактирования контента)
# @dependencies: config/content/posts.schema.yaml, config/app.yaml
# @created: 2025-08-19

version: "1.0.0"
posts:
  - id: 1
    text_key: post_1
    image:
      url: https://photos.app.goo.gl/ww5ogWa1f2k4iHYA9
      caption: |
        <b>ИИ уже здесь: не будущее, а настоящее</b>

        🔥 Вот правда, которую скрывают:

        ИИ - это не твой конкурент. Это твой личный креативный ассистент, который работает 24/7 и никогда не устаёт генерировать идеи.

        Представь:
        • Ты придумываешь концепцию за 5 минут вместо 2 часов
        • Создаёшь 10 вариантов контента, пока конкуренты мучаются с одним
        • Масштабируешь идеи со скоростью света

        <b>ТЫ остаёшься режиссёром своего успеха.</b> ИИ просто даёт тебе суперсилы 🚀

        ❗️ <b>Но есть одна проблема:</b> 90% людей используют ИИ неправильно и получают посредственный результат.

        Хочешь узнать, как войти в те самые 10%, которые уже переписали правила игры?

        👇 Жми на кнопку - покажу систему, которая превратит тебя в креативную машину нового поколения.

        P.S. Пока ты думаешь, твои конкуренты уже учатся.
    buttons:
      - label: "📥 Получить"
        action: material
        url: https://disk.yandex.ru/d/wzJp1dkEs4UDHw
      - label: "🛠️ Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "🌐 Стать ПервоPROходцем"
        action: community
        message: "Изучи материалы, которые мы собрали для тебя совершенно бесплатно. Тогда узнаешь как попасть в сообщество. Всего 5 постов"
      - label: "🧠 Хочу изучать нейросети"
        action: jump
        target_post: 6

  - id: 2
    text_key: post_2
    image:
      url: https://photos.app.goo.gl/x4mvn8SFfUk9o17f7
      caption: |
        🚀 <b>Секрет миллионеров: как превратить ИИ в своего личного гения</b>

        Пока 90% людей спорят "заменит ли ИИ человека", умные уже зарабатывают с ним миллионы.

        Например, <b>Райан Кан</b> (YouTube, 12M подписчиков) генерирует с ИИ 50+ идей для роликов за 10 минут и зарабатывает $2M в год!

        Его секрет? Он знает, как правильно "дрессировать" ИИ 🎯

        💎 <b>3 ХАКА, которые превратят ChatGPT в твоего топ-менеджера:

        🔹 Хак #1: Говори как с CEO</b>

        "Создай пост для IT-предпринимателей 25-40 лет, который увеличит продажи SaaS-продукта на 30%. Используй принцип дефицита и социального доказательства"

        🔹 <b>Хак #2: Загрузи "базу знаний"</b>

        Скинь ИИ 5-7 лучших примеров и скажи: "Изучи паттерны успеха в этих текстах и копируй их структуру"

        🔹 <b>Хак #3: Создай "давление"</b>

        "От этого зависит сделка на 5 млн рублей". ИИ включает турбо-режим, когда чувствует важность.

        👇Нажиимай на кнопку с материалами - пришлю подборку лучших сервисов!
    buttons:
      - label: "📚 Получить"
        action: material
        url: https://disk.yandex.ru/d/t5nrMkz-LXcdPA
      - label: "💬 Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "🤝 Стать ПервоPROходцем"
        action: community
        message: "Изучи материалы, которые мы собрали для тебя совершенно бесплатно. Тогда узнаешь как попасть в сообщество. Всего 5 постов"

  - id: 3
    text_key: post_3
    image:
      url: https://example.com/images/post3.jpg
      caption: |
        <b>Почему мы назвали проект "Нейроход"?</b>

        На самом деле всё просто. Помните, как в детстве учились ходить? Конечно же нет, но было примерно так: сначала ползали, потом вставали, держась за диван, делали первый шаг... падали... снова вставали. И так до тех пор, пока ходьба не стала естественной.

        С нейросетями — точно так же.

        Большинство людей пытаются сразу "побежать": скачали ChatGPT и ждут магии. А получают банальщину. Расстраиваются. Говорят "ИИ — это фигня".
        А дело в том, что пропустили этап "обучения ходьбе".

        🧠 Каждый наш "нейрошаг" — это микронавык:

        • Как правильно формулировать задачу (а не "напиши что-нибудь про маркетинг")
        • Как "загружать" контекст в нейросеть
        • Как заставить ИИ задавать уточняющие вопросы
        • Как превратить ChatGPT в личного аналитика
        • Как создавать визуалы, которые не стыдно показать клиентам

        Когда освоишь базовые "нейрошаги", начинаешь видеть возможности везде. И это не магия. Это просто правильные "шаги".

        🎯 Самое важное:

        Мы не просто рассказываем "как пользоваться ChatGPT". Мы передаём навык думать в связке с ИИ.
    buttons:
      - label: "🧩 Получить"
        action: material
        url: https://disk.yandex.ru/d/d-_byWMdgaRk_w
      - label: "🛟 Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "🏛️ Стать ПервоPROходцем"
        action: community
        message: "Изучи материалы, которые мы собрали для тебя совершенно бесплатно. Тогда узнаешь как попасть в сообщество. Всего 5 постов"

  - id: 4
    text_key: post_4
    image:
      url: https://example.com/images/post4.jpg
      caption: |
        <b>Реальные истории: как ИИ меняет жизнь</b>
        
        🌟 Вот пара историй:
        — Анна, маркетолог: "ИИ помог за 5 минут сделать аналитику, на которую раньше уходил час!"
        — Иван, предприниматель: "Нейросеть сгенерировала рекламный текст, который привёл новых клиентов."
        
        ⠀ А как ИИ мог бы изменить вашу работу или повседневные задачи?
        👇 Поделитесь своей историей или ожиданиями — самые интересные разберём вместе!
    buttons:
      - label: "🗂️ Получить"
        action: material
        url: https://disk.yandex.ru/d/rbOO2PiqNuvY2Q
      - label: "🆘 Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "🌱 Стать ПервоPROходцем"
        action: community
        message: "Изучи материалы, которые мы собрали для тебя совершенно бесплатно. Тогда узнаешь как попасть в сообщество. Всего 5 постов"

  - id: 5
    text_key: post_5
    image:
      url: https://example.com/images/post5.jpg
      caption: |
        <b>Диагностика: где ИИ принесёт максимальную пользу именно вам</b>
        
        🔍 Не знаете, с чего начать? Давайте разберёмся вместе!
        ⠀ Пройдите короткую диагностику — и узнаете, какие нейросети подойдут именно для ваших задач:
        — Автоматизация рутины
        — Создание контента
        — Аналитика и отчёты
        — Личное планирование
        
        ⠀ Хотите получить индивидуальную подборку инструментов?
        👇 Нажимай "Получить пользу" — и получите чек-лист с рекомендациями!
    buttons:
      - label: "🧾 Получить"
        action: material
        url: https://disk.yandex.ru/d/myEpsm4TOzx6uw
      - label: "📞 Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "🧠 Стать ПервоPROходцем"
        action: community
        message: "Изучи материалы, которые мы собрали для тебя совершенно бесплатно. Тогда узнаешь как попасть в сообщество. Всего 5 постов"

  - id: 6
    text_key: post_6
    image:
      url: https://example.com/images/post6.jpg
      caption: |
        <b>Готовы к следующему уровню? Присоединяйтесь к сообществу!</b>
        
        🎯 Вы прошли путь от новичка до продвинутого пользователя ИИ. Теперь самое время присоединиться к сообществу единомышленников!
        
        ⠀ В нашем закрытом сообществе вы получите:
        — Эксклюзивные материалы и кейсы
        — Поддержку экспертов
        — Сетевые возможности
        — Доступ к новейшим инструментам
        
        ⠀ Готовы стать частью будущего?
        👇 Нажмите "Присоединиться" — и получите доступ к закрытому сообществу!
    buttons:
      - label: "💳 Оплатить"
        action: payment
        price: 8700
        currency: RUB
        provider: yookassa
      - label: "🛟 Техподдержка"
        action: support
        url: https://t.me/ArthurMacArthur
      - label: "📋 Условия"
        action: community
        message: "Подробные условия участия в сообществе и все преимущества для участников"
